### PR TITLE
Adding the proper way to do resource precache

### PR DESCRIPTION
**Pull request by Yarukon**
# (edit: tested on linux)
from CS2Fixes

example:
``` C#
RegisterListener<Listeners.OnServerPrecacheResources>((manifest) =>
{
    manifest.AddResource("path/to/model");
    manifest.AddResource("path/to/material");
    manifest.AddResource("path/to/sound");
});
```

warning:
this will only be called when initial startup / changing map

improvement:
maybe find a better way to do the event

### CODE REVIEW

**Comment by KillStr3aK** [comment]
LGTM, and finally!

**Comment by roflmuffin** [comment]
@KillStr3aK Have you tried this on Linux or would you like me to

**Comment by KillStr3aK** [comment]
> @KillStr3aK Have you tried this on Linux or would you like me to

I would like you to do so

**Comment by Yarukon** [comment]
@roflmuffin i've tested on linux and it works fine
Snipaste_2024-03-02_07-27-00

**Review by roflmuffin — APPROVED** [review]

**Pull request merged**
