### PR TITLE
Fix: new game update broke signatures 

### PR DESCRIPTION
**Pull request by KillStr3aK**
Lets collect the new signatures in this pr then we can merge it in one

### CODE REVIEW

**Comment by KillStr3aK** [comment]
opened pr on my fork by accident firstly haha

**Comment by KillStr3aK** [comment]
`CCSPlayerPawnBase_PostThink` needed

**Comment by KillStr3aK** [comment]
Windows signatures by @Yarukon 
as I can see only these have changed, we need the linux version of these

**Comment by Nianmou** [comment]
`Killplayer.PlayerPawn.Value.ArmorValue = 100;` and Timers and `player.PlayerPawn.Value.Bot.IsCrouching`There are problems with everything

**Comment by KillStr3aK** [comment]
> `Killplayer.PlayerPawn.Value.ArmorValue = 100;` and Timers and `player.PlayerPawn.Value.Bot.IsCrouching`There are problems with everything

these are unrelated to signatures

**Comment by Nianmou** [comment]
> > `Killplayer.PlayerPawn.Value.ArmorValue = 100;`和计时器和`player.PlayerPawn.Value.Bot.IsCrouching`一切都有问题
> 
> 这些与签名无关

Is it a problem with CCSPlayerPawnBase, as after the update, running one of these will cause the server to crash

**Comment by KillStr3aK** [comment]
`CGameRules_TerminateRound` on linux is good

**Comment by Kroytz** [comment]
> > > `Killplayer.PlayerPawn.Value.ArmorValue = 100;`和计时器和`player.PlayerPawn.Value.Bot.IsCrouching`一切都有问题
> > 
> > 
> > 这些与签名无关
> 
> Is it a problem with CCSPlayerPawnBase, as after the update, running one of these will cause the server to crash

SchemaSystem更新了一些字段. 以及有的CHandle确实好像拿的有问题.

**Comment by KillStr3aK** [comment]
`CBasePlayerPawn_RemovePlayerItem` is fine on linux, ready

**Review by roflmuffin — APPROVED** [review]

**Pull request merged**
