### PR TITLE
Draft: Feature/shipped plugins

### PR DESCRIPTION
**Pull request by B3none**
Plugins left to convert:
- [ ] [admin-flatfile.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/admin-flatfile.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [admin-sql-prefetch.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/admin-sql-prefetch.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [admin-sql-threaded.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/admin-sql-threaded.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [adminhelp.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/adminhelp.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [adminmenu.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/adminmenu.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [antiflood.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/antiflood.sp)
    - [x] Port plugin @B3none
    - [ ] Documentation

- [ ] [basebans.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/basebans.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [basechat.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/basechat.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [basecomm.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/basecomm.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [basecommands.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/basecommands.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [basetriggers.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/basetriggers.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [basevotes.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/basevotes.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [clientprefs.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/clientprefs.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [compile.sh](https://github.com/alliedmodders/sourcemod/blob/master/plugins/compile.sh)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [funcommands.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/funcommands.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [funvotes.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/funvotes.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [mapchooser.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/mapchooser.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [nextmap.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/nextmap.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [nominations.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/nominations.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [playercommands.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/playercommands.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [randomcycle.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/randomcycle.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [reservedslots.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/reservedslots.sp)
    - [x] Port plugin @B3none
    - [ ] Documentation

- [ ] [rockthevote.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/rockthevote.sp)
    - [ ] Port plugin @abnerfs 
    - [ ] Documentation

- [ ] [sounds.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/sounds.sp)
    - [ ] Port plugin
    - [ ] Documentation

- [ ] [sql-admin-manager.sp](https://github.com/alliedmodders/sourcemod/blob/master/plugins/sql-admin-manager.sp)
    - [ ] Port plugin
    - [ ] Documentation

### CODE REVIEW

**Comment by ItsChase88** [comment]
https://discord.com/channels/1160907911501991946/1177199605864210472

I still feel like there shouldn't be bloatware included with CS#, but that is my personal opinion. These should 100% be made and released as plugins but shipping them with CS# I feel like is unnecessary.

**Comment by B3none** [comment]
> https://discord.com/channels/1160907911501991946/1177199605864210472
> 
> I still feel like there shouldn't be bloatware included with CS#, but that is my personal opinion. These should 100% be made and released as plugins but shipping them with CS# I feel like is unnecessary.

Here are the images with the discord discussion:
image
image
image

**Comment by pedrotski** [comment]
This has been discussed before, and it was decided against. Adding these only cause bloat that would get replaced by superior options once they come out (look at the most popular plugins for CSGO for example). Furthermore, most of this makes no sense to add to CS#. 

CS# is and should only be a modding framework, not trying to be a jack of all trades and edge cases.

**Comment by zonical** [comment]
Here are my two cents after discussions on Discord. The consensus amongst developers is that including plugins in the base repository would create bloat (which I don't strictly agree with, but that's not my point) and that constantly removing the base plugins after updates would be annoying (fair).

My solution is this: We create a recommendations list for plugins. This list would consist of well-maintained, well-designed and up-to-date plugins created by community members or people with developer access (like myself or B3none). If people need to find a plugin to solve a problem (e.g. admin commands), we could easily point them towards one or two plugins on the list. This list of plugins could be contained in a submodule on the repository and updates can be fed towards that submodule instead of constantly creating releases. That submodule could also provide a `.sln` file so people can easily compile plugins and make their adjustments or forks if desired. There would have to be a set of standards relating to good code practices, determining if a project is well-maintained, how to submit, but that can be worked out at a later point in time.

**Comment by roflmuffin** [comment]
Reposting my message from Discord:

I think @B3none's head is in the right place; they are trying to instigate this as a way for community members to contribute to the official CS# codebase, but I think I am in agreement that if we were to create a set of official plugins, they should not live inside the CS# repo.

Eventually I plan on moving the main CounterStrikeSharp repo to an organisation, at which point we can think about creating a set of CS#+ (who doesn't love more symbols!) tools & plugins. I do think these kinds of plugins serve as a good "real world" example of best practices & paradigms so they are useful in that sense anyway.

Until then, I think the ⁠✨・plugin-releases  channel is sufficient for server owners to find plugins they are looking for (albeit still with the need to pin the top message of each thread).

**Pull request closed without merging**
