### PR TITLE
PrintCenterHtml - Duration param

### PR DESCRIPTION
**Pull request by Mbk10201**
A small change but that will solve a lot of things on bigger game modes.

### CODE REVIEW

**Comment by KillStr3aK** [comment]
this needs to be up to date with the current branch

**Comment by HerrMagiic** [comment]
please update🙏

**Comment by roflmuffin** [comment]
I am unsure if changing the second parameter to a defaulted argument will break existing compat

**Comment by Mbk10201** [comment]
> I am unsure if changing the second parameter to a defaulted argument will break existing compat

Why will it break ? i don't see any issue

**Comment by Mbk10201** [comment]
Alright i've fixed the conflicts

**Comment by Mbk10201** [comment]
@roflmuffin Heyy, Can you merge it ?

**Comment by roflmuffin** [comment]
Anyone who was previously calling PrintToCenterHtml with no duration argument will fail until they recompile. You will need to make an overloaded version of the function so that both prototypes are supported.

**Pull request closed without merging**
