### PR TITLE
fix: armory update broken signatures and offsets

### PR DESCRIPTION
**Pull request by KillStr3aK**
~~We still miss `StateChanged` and `CCSPlayer_WeaponServices_CanUse` is unreliable on windows, linux is fine according to gdc~~

~~No idea if there is any broken offset but I guess so~~
fixed offsets:
- [CBaseEntity_Teleport](https://github.com/roflmuffin/CounterStrikeSharp/pull/584/commits/56059e852b2d25e01f392b124933e2b704f3af4c)
- [CCSPlayerController_ChangeTeam](https://github.com/roflmuffin/CounterStrikeSharp/pull/584/commits/f70cc33fcfccca116a9bd635ddcb3563346c98e2)
- [CBasePlayerPawn_CommitSuicide](https://github.com/roflmuffin/CounterStrikeSharp/pull/584/commits/a66c94902ed33e25b31dc98a3a431cc724f6e075)
- [CCSPlayer_ItemServices_DropActivePlayerWeapon](https://github.com/roflmuffin/CounterStrikeSharp/pull/584/commits/8cec48467dfc90da939dbdabda795a54e920b0c1)
- [CCSPlayer_ItemServices_GiveNamedItem](https://github.com/roflmuffin/CounterStrikeSharp/pull/584/commits/fadd9d7a66393698016712613150c20cfc508231)
- [CCSPlayerController_Respawn](https://github.com/roflmuffin/CounterStrikeSharp/pull/584/commits/ca010023c772d204f53f913866c0467a0955c8d1)
- [CCSPlayer_ItemServices_RemoveWeapons](https://github.com/roflmuffin/CounterStrikeSharp/pull/584/commits/bf1142d8a1d2e8d7949fbc66e7349fa7d7a53b46)

_most of the signatures are from stefanx_

### CODE REVIEW

**Comment by KillStr3aK** [comment]
when this is shipped, and we got a new build with the latest metamod (no eta) #583 should be fixed

**Comment by crltysdk** [comment]
Someone build a metamod fix but not official and of course there will be missing few things but u can maybe give it a try.
[metamod.zip](https://github.com/user-attachments/files/17245911/metamod.zip)

**Comment by KillStr3aK** [comment]
> Someone build a metamod fix but not official and of course there will be missing few things but u can maybe give it a try. [metamod.zip](https://github.com/user-attachments/files/17245911/metamod.zip)

Note that everyone should be careful on what executables they are downloading from someone since malware could be mixed in in these binaries. If you are not sure, or want to be careful, just be patient and wait for an official release.

**Comment by crltysdk** [comment]
> > Someone build a metamod fix but not official and of course there will be missing few things but u can maybe give it a try. [metamod.zip](https://github.com/user-attachments/files/17245911/metamod.zip)
> 
> Note that everyone should be careful on what executables they are downloading from someone since malware could be mixed in in these binaries. If you are not sure, or want to be careful, just be patient and wait for an official release.

Yeah i know this, it was posted in the alliedmodders dc. It was tested, so mm works with this, but i'll bet there must be more changes to the whole system to work. And the plugins maybe also be recompiled, so it will take a few days like last big update to get everything working properly.

**Comment by KillStr3aK** [comment]
> server crashes when map changes sig could be corrupted?

the crash issue is with the custom built metamod, it has been mentioned on the AM discord aswell

**Comment by tdziero** [comment]
> Someone build a metamod fix but not official and of course there will be missing few things but u can maybe give it a try. [metamod.zip](https://github.com/user-attachments/files/17245911/metamod.zip)

I downloaded these versions and still nothing

**Comment by igorgusarov** [comment]
Unstable metamod build 1314 seems to be working.

**Comment by LionDoge** [comment]
`CBaseEntity_Teleport` looks to be offset 157 for Linux and Windows. I haven't verified fully, so if someone can confirm then it would be appreciated.

**Comment by vitordarela** [comment]
> `CBaseEntity_Teleport` looks to be offset 157 for Linux and Windows. I haven't verified fully, so if someone can confirm then it would be appreciated.

Hello, I tested with 157 for Windows and Linux, but the positions are outside the map, the player is being rendered below, but the server no longer crashes.

**Comment by gha241** [comment]
IMG_20241004_071240

**Comment by qw1n175** [comment]
{37294779-BD19-46C1-80E7-265DE3382A02}

**Review by roflmuffin — APPROVED** [review]

**Pull request merged**
