### PR TITLE
fixed some signatures, and signature order

### PR DESCRIPTION
**Pull request by KillStr3aK**
windows::CBasePlayerController_SetPawn
linux::CBaseModelEntity_SetModel
linux::CBaseTrigger_EndTouch
linux::CBaseEntity_Teleport

`LegacyGameEventListener` is mixed with `AcceptInput`? haven't found any new signature for that but its crashy

### CODE REVIEW

**Comment by xLeviNx** [comment]
LegacyGameEventListener is also wrong:

[gamedata.json](https://github.com/roflmuffin/CounterStrikeSharp/files/14209639/gamedata.json)
`  "LegacyGameEventListener": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x8B\\x15\\x2A\\x2A\\x2A\\x2A\\x48\\x85\\xD2\\x74\\x2A\\x85\\xC9\\x74",
      "linux": "\\x48\\x8B\\x05\\x2A\\x2A\\x2A\\x2A\\x48\\x85\\xC0\\x74\\x2A\\x83\\xFF\\x3F\\x76\\x2A\\x31\\xC0"
    }
  },`

**Comment by KillStr3aK** [comment]
someone has sent signatures for legacy but its still crashing with that afaik

**Comment by Yarukon** [comment]
isn't the original LegacyGameEventListener still working?

**Comment by xLeviNx** [comment]
> someone has sent signatures for legacy but its still crashing with that afaik

I've tested it with the current signature and its working afaik. Questionable on changeteam if that sig is correct

**Comment by Yarukon** [comment]
CCSPlayerController_ChangeTeam on windows is 93 but i havent tested yet

**Comment by zonical** [comment]
Apologies for my blind ignorance when constructing last night's PR. SetModel and EndTouch worked perfectly fine on my Linux server with everything updated. Really strange.

**Comment by KillStr3aK** [comment]
> isn't the original LegacyGameEventListener signature still working?

the one in this pr does not

**Comment by xLeviNx** [comment]
> Apologies for my blind ignorance when constructing last night's PR. SetModel and EndTouch worked perfectly fine on my Linux server with everything updated. Really strange.

No worries, its broken again haha

**Comment by criskkky** [comment]
> > Apologies for my blind ignorance when constructing last night's PR. SetModel and EndTouch worked perfectly fine on my Linux server with everything updated. Really strange.
> 
> No worries, its broken again haha

https://discord.com/channels/1160907911501991946/1160907912445710479/1205316773591777291

**Comment by xLeviNx** [comment]
[gamedata.json](https://github.com/roflmuffin/CounterStrikeSharp/files/14216124/gamedata.json)

**Comment by roflmuffin** [comment]
I've merged Levin's gamedata into main, so closing this one

**Pull request closed without merging**
