### PR TITLE
Feature/localization rework

### PR DESCRIPTION
**Pull request by Dliix66**
Added some more methods to simplify localization out of a command's context

### CODE REVIEW

**Comment by roflmuffin** [comment]
Looks okay to me, might be worth adding a XML doc comment to the methods and updating the example plugin?

**Comment by Dliix66** [comment]
I can do that 👍

**Comment by frederikstonge** [comment]
Sine IStringLocalizer can be injected in other classes, would it not be better to create extension methods on IStringLocalizer?

**Comment by Dliix66** [comment]
@roflmuffin I updated the example plugin and this should be available in the docs too.

**Comment by roflmuffin** [comment]
I've added these as extension methods in build #258, which I think is cleaner/more extensible than amending the base class in this PR.

**Pull request closed without merging**
