### PR TITLE
[Windows] feat: Windows support

### PR DESCRIPTION
**Pull request by laper32**
#1 
Warning: Only tested on Windows, I'm not pretty sure whether these changes will break linux build.
Special thanks to @Ciallo-Ani, which helps us a lot to make a huge progress.

### CODE REVIEW

**Comment by laper32** [comment]
Seems that everything is ready. Let's GO!

**Comment by laper32** [comment]
Let's GO!

**Comment by roflmuffin** [comment]
Would you be able to remove some of the extra unnecessary console writelines in the managed side.

**Comment by laper32** [comment]
> Would you be able to remove some of the extra unnecessary console writelines in the managed side.

done

**Comment by roflmuffin** [comment]
Thanks so much for this, I will pull down and test Linux as soon as possible and then look at CI

**Comment by roflmuffin** [comment]
There are still quite a few build errors, mostly int he dotnet_host on linux side, mostly to do with the string types. Did you want me to takeover or are you happy to resolve them. They should show up in CI for the latest commit.

**Comment by laper32** [comment]
just go ahead， since I dont have linux machine right now

**Comment by laper32** [comment]
I think I've compiled all compiler issues, based on by CI

**Pull request merged**
